@LogTimeWeb.Server_HostAddress = http://localhost:5109/LogTimeWeb/session

POST {{LogTimeWeb.Server_HostAddress}}/ValidateUser

Accept: application/json
Content-Type: application/json

{"userId": "2929","password": "dsdsdsd"}

###
